openapi: 3.0.3
info:
  title: Formula1 system 
  version: 1.0.0
  contact:
    email: denny.truongnguyen@gmail.com
servers:
  - url: http://localhost:3000/api


paths:
  /movies:
    get:
      tags:
        - movie
      summary: Get all movie entities
      responses:
        '200':
          description: successfull
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
    post: 
      tags:
        - movie 
      summary: Create movie entity 
      requestBody:
        description: Create a new movie entity
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/MovieRequest'
      responses:
        '201':
          description: created
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/Movie'
  /movies/{id}:
    get:
      tags:
        - movie
      summary: Get a movie
      description: get a movie
      parameters:
        - name: id
          in: path
          description: movie id to get
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid movie value
        '200':
          description: Get movie
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/Movie'
    
    delete:
      tags:
        - movie
      summary: Deletes a movie
      description: delete a movie
      parameters:
        - name: id
          in: path
          description: movie id to delete
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid movie value
        '204':
          description: No content
    
    put:
      tags:
        - movie
      summary: Update a movie
      description: update a movie
      parameters:
        - name: id
          in: path
          description: movie id to delete
          required: true
          schema:
            type: string
      requestBody:
        description: Create a new movie entity
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/MovieRequest'      
      responses:
        '400':
          description: Invalid movie value
        '200':
          description: updated
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/Movie'



components:
  schemas:
    MovieRequest: 
      type: object
      properties:
        title: 
          type: string
        genre: 
          type: array
          items:
            type: string
        year: 
          type: string
    Movie:
      allOf: 
      - $ref: '#/components/schemas/MovieRequest'
      - type: object
        required:
        - id
        properties:
          id:
            type: string
  securitySchemes:
    jwt_token:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT  

security: 
  - jwt_token: []